<li><a href="Specialized_Spirituality_Testimonials-Overview.php">Overview</a></li>
<span class="vert">&vert;</span>
<li><a href="leaders\GeneralWorkshops_Leaders-Arbogast.php">David Arbogast</a></li>
<span class="vert">&vert;</span>
<li><a href="GeneralWorkshops_Leaders-Progoff.php">Jon Progoff</a></li>
<span class="vert">&vert;</span>
<li><a href="leaders\GeneralWorkshops_Leaders-Evard.php">Virginia Evard</a></li>
<span class="vert">&vert;</span>
<li><a href="leaders\GeneralWorkshops_Leaders-Graul-Bellali.php">Heidimarie Graul-Bellali</a></li>
<span class="vert">&vert;</span>
<li><a href="leaders\GeneralWorkshops_Leaders-Hackett.php">Joanne Hackett Ching</a></li>
<span class="vert">&vert;</span>
<li><a href="leaders\GeneralWorkshops_Leaders-Israel.php">William Israel</a></li>
<span class="vert">&vert;</span>
<li><a href="leaders\GeneralWorkshops_Leaders-Jeffers.php">Joseph Jeffers</a></li>
<span class="vert">&vert;</span>
<li><a href="leaders\GeneralWorkshops_Leaders-Ladas-Gaskin.php">Carol Ladas-Gaskin</a></li>
<span class="vert">&vert;</span>
<li><a href="leaders\GeneralWorkshops_Leaders-Mitch.php">Dolores Mitch</a></li>
<span class="vert">&vert;</span>
<li><a href="leaders\GeneralWorkshops_Leaders-Nimmich.php">Nancy-Elizabeth Nimmich</a></li>
<span class="vert">&vert;</span>
<li><a href="leaders\GeneralWorkshops_Leaders-Scholl.php">Kate Scholl</a></li>
<span class="vert">&vert;</span>
<li><a href="leaders\GeneralWorkshops_Leaders-Wemhoff.php">Evelyn Wemhoff</a></li>
<span class="vert">&vert;</span>
<li><a href="leaders\GeneralWorkshops_Leaders-Williams.php">Carolyn Williams</a></li>
<span class="vert">&vert;</span>
<!--  <li><a href="testimonials\Specialized_Spirituality_Testimonials-Unity.php">Kate Scholl</a></li>
<span class="vert">&vert;</span>-->
